{********************************************************************

  OOGrid Library(TM) for Borland/Turbo Pascal (Real Mode/TV)
  Copyright (C) 1994, 1995 by Arturo J. Monge
  Portions Copyright (C) 1989,1990 Borland International, Inc.

  Description:
    Program used to build all units in the library.

  Copyright (C) 1994, 1995 by Arturo J. Monge

  Last Modification : February 3rd, 1995

*********************************************************************}


program Build_OOGrid_Library(TM);

uses
  GlCell,
  GLEquate,
  GLLStr,
  GLParser,
  GLSort,
  GLSupprt,
  GLTSheet,
  GLTVR_US,
  GLTVR_SP,
  GLViews,
  GLWindow,
  TCHash,
  TCUtil;

begin
end.