unit HELPCTX;

interface

const

  hcCancel               = 12;
  hcContents             = 0;
  hcHelpIntro            = 5;
  hcHelpOnHelp           = 2;
  hcOK                   = 11;
  hcOld                  = 7;
  hcRezIntro             = 6;
  hcTopicA               = 8;
  hcTopicB               = 9;
  hcTopicC               = 10;
  hctoyCSBackground      = 36;
  hctoyCSForeground      = 37;
  hctoyCSGroup           = 38;
  hctoyCSItem            = 39;
  hctoyCSMonoSelector    = 40;
  hctoyCSPropagation     = 41;
  hctoyFontDialogHelp    = 27;
  hctoyFontListBox       = 26;
  hctoyHHelp             = 28;
  hctoyHPreviousTopic    = 29;
  hctoyHUsingHelp        = 30;
  hctoyOVideoTests       = 31;
  hctoyV14p              = 16;
  hctoyV16p              = 17;
  hctoyV8p               = 18;
  hctoyVideoDialogHelp   = 19;
  hctoyVideoListBox      = 20;
  hctoyVideoPreview      = 21;
  hctoyVideoRescan       = 22;
  hctoyVPBlue            = 32;
  hctoyVPDialogHelp      = 35;
  hctoyVPGreen           = 33;
  hctoyVPRed             = 34;
  hctoyVSelectFont       = 15;
  hctoyVTCheckV7         = 24;
  hctoyVTCheckVesa       = 23;
  hctoyVTDialogHelp      = 25;
  hctoyVVideoLines       = 13;
  hctoyVVideoMode        = 14;
  hcUsingHelp            = 3;
  hcVideoIntro           = 4;

implementation

end.
